### ISSUE TITLE
您好，可以分享一下代码吗，非常感谢！！

### ISSUE THREAD

**Issue by zhangronghuan** [xwmaxwma/rssegmentation#2]

**Comment by xwmaxwma** [comment]
你需要哪个论文的代码。我可以先分享你模型部分。我最近在实习比较忙，全部代码还没整理好。

**Comment by zhangronghuan** [comment]
就是LOG-CAN: LOCAL-GLOBAL CLASS-AWARE NETWORK FOR SEMANTIC SEGMENTATION OF REMOTE SENSING IMAGES这一篇的代码,非常感谢

**Comment by xwmaxwma** [comment]
已更新
