### ISSUE TITLE
ERROR in LoveDA Train

### ISSUE THREAD

**Issue by GluttonK** [xwmaxwma/rssegmentation#4]
when I train the model with LoveDA Dataset, I got error 
NLLLoss2d.cu:103: block: [6,0,0], thread: [1011,0,0] Assertion `t >= 0 && t < n_classes` failed.
I would like to know if you have successfully trained the model using the LoveDA dataset
and if I should process the labels
Thank you

**Comment by xwmaxwma** [comment]
已更新。之前的loveda数据集上的config有点问题，下载新的configs即可
